### ISSUE TITLE
regarding dataset

### ISSUE THREAD

**Issue by sweetyshetty08** [jicksy/Online-Food-Ordering#1]
hi jicksy, can you attach sql file related to this project. We need this to understand this project in a better way.
Thanks in Advance:)

**Comment by ngethe** [comment]
I need this as well :) :+1:  please

**Comment by jicksy** [comment]
Hi, @sweetyshetty08 @ngethe ,
I have added the dataset. Luckily it was available in my project export! :) Thanks for pointing it out. 
@sweetyshetty08, sorry for replying so late. Had missed out this issue thread till today.

**Comment by jicksy** [comment]
@sweetyshetty08 @ngethe , SQL file is already there. Please check https://github.com/jicksy/Online-Food-Ordering/blob/master/restraunt.sql
